### ISSUE TITLE
Few improvements

### ISSUE THREAD

**Issue by gits-up** [prrockzed/nvimDev#14]
1. Documentation:

The INSTALL.md file could be expanded with detailed setup instructions, plugin descriptions, and usage examples for new users.

2. Plugin Management:

There are files for plugin configuration under plugin_config. I want to add support for more popular plugins, optimize the current setup, or streamline plugin loading for faster startup.
The lazy.lua file indicates lazy loading of plugins. I want to improve how plugins are lazily loaded or ensuring compatibility with more plugins could enhance performance.

3. Keybindings & Options:

I want to suggest improvements or additions to the keymaps.lua for better usability.
Want to optimize or expand configurations in options.lua to enhance the Neovim experience.

4. Color Schemes:

Under color_config, I can add support for more themes or improve the current color configuration by testing in various environments (light and dark modes). Although this is something I need to discuss with you ig.

Please assign me this :)

**Comment by prrockzed** [comment]
I don't think that the Install.md needs attention at this stage of the project, especially not for setup as there is no setup required as of now(just install and use, coz i hv not added LSP yet), but still if you still think so about plugin desc and usage example, do give it a try.

As for plugin management, please specify which plugins and are you planning to use. I am particularly enthusiastic about this point. Make sure to include atleast 4-5 plugins.

For keybindings and options, i don't think more keybinding or options is required, but i am open to new and 'useful' keybinding(which is not there in which-key file)

Go ahead with the color scheme and add only those colorschemes which are pleasing to the eyes and not any random ones.

If I approve of all 4 ideas(or even only pts 2,3,4), then this will definitely get a level3 label. Otherwise a level2 one. But first inform me about your ideas in detail here.
I am assuming you have used Neovim before. And know about the folder structure of this project. If there is any query regarding anything, do ask.

Also if you have a windows system, do check out my windows support issue(would be glad if you can sort that one out).

**Comment by gits-up** [comment]
1. Install.md Consideration
Since you mentioned there's no need for complex setup documentation at this stage, I’d agree to keep the install section minimal for now. You can revisit adding plugin descriptions and usage examples when LSP or more advanced features come into play. For now, I'll shift focus to the areas you're particularly enthusiastic about.

2. Plugin Management (Core Plugins)
Here’s a focused approach to plugin management. I suggest using lazy.nvim for plugin handling (since it’s already integrated). I’ll propose 4-5 core plugins that are both lightweight and useful for your workflow:

Telescope.nvim: For fast fuzzy finding, file search, and general navigation.
Lualine.nvim: A customizable status line that integrates well with most plugins.
Nvim-tree.lua: A file explorer for easier project navigation.
Which-key.nvim: For mapping hints and improving discoverability of keybindings.
Gitsigns.nvim: For Git integration, inline blame, and file diffs.

3. Keybindings
You already have a nice set of keybindings, but here are a few additional bindings that I think would be useful without duplicating existing functionality:

Toggle File Explorer: A shortcut to open/close nvim-tree.
Toggle Gitsigns Diff: Quickly check diffs with Git.
Toggle Comments: A mapping for commenting lines or blocks.
Open Telescope File Search: Faster access to Telescope’s fuzzy finder.

4. 4. Color Schemes (Visually Pleasing)
I’d recommend a few handpicked color schemes that are easy on the eyes, which you might find pleasing:

Catppuccin: A soft pastel color palette with various flavors (e.g., macchiato, mocha).
OneDarkPro: A dark theme based on Atom's One Dark, great contrast and readability.
Gruvbox: A retro groove palette with both dark and light variants, well-loved in the community.
Tokyo Night: A minimal dark theme inspired by VS Code’s Tokyo Night, designed for low-light environments.
Yea I know some of them are already there but yea.

I will look into windows error too.

**Comment by prrockzed** [comment]
Apart from Gitsigns, i am afraid i have implemented all other plugins already. And as for keybindings, i have again implemented all the keybingings in which-key file. Only those of toggle comments and toggle gitsigns is not implements.

So your suggestion is brought down to only installing 2 plugins, which are Gitsigns and comment nvim plugins. These are ok. If you can add 2 more plugins which are not used in the project(search in the web), then I can give it a level 2 label, otherwise it is a level 1.

**Comment by gits-up** [comment]
How about these two:
1. Hop.nvim - A fast and easy-to-use motion plugin for Neovim that helps you jump to any word or line in the file with fewer keystrokes. It enhances navigation significantly.
2. nvim-autopairs - This plugin automatically inserts matching pairs like (), {}, and []. It’s great for improving the coding experience and reducing the need for manually closing parentheses, brackets, or quotes.

**Comment by prrockzed** [comment]
for Hop.nvim, no. I have already implemented that feature via telescope and created a keybinding too for it in which key. 

Go aheah with nvim autopairs, gitsigns and comment nvim plugins. These plugins have to be installed in the dump_plugins folder and their default configurations too in the plugin_config directory. There are tons of neovim plugins in the net. You can search for some good plugins in awesome neovim plugins too(a github repo).

**Comment by gits-up** [comment]
I added-


nvim-autopairs
Gitsigns.nvim
Comment.nvim

**Comment by prrockzed** [comment]
ok. Have you added their default config as well? And do a pull request.

**Comment by gits-up** [comment]
Yes, I have added the default configuration for nvim-autopairs, Gitsigns.nvim, and Comment.nvim.
