### ISSUE TITLE
Adding Code_of_conduct file

### ISSUE THREAD

**Issue by Nikhil0-3** [prrockzed/nvimDev#29]
Adding code of conduct file helps contributor to understand what rules and regulations they needs to be follow.
Here are the some points I want to add in this file:-

How to contribute (fix bugs, add features)
Steps for submitting changes
Project setup instructions
Rules for code style
Code of conduct for respectful behavior
Enhance the project structure
Add the help and support section
Add the pull request section
Add issue report process section

**Comment by Nikhil0-3** [comment]
Please assign this issue to me, I would like to work on that.

**Comment by prrockzed** [comment]
Ok. Please tell me why should i assign you the issue. Just curious: Have you gone through the project's readme?
I really encourage people to first go through the project's readme and then raise any issue.

Once you have gone through the readme, inform me and then i will assign you the issue.

**Comment by Nikhil0-3** [comment]
> Ok. Please tell me why should i assign you the issue. Just curious: Have you gone through the project's readme? I really encourage people to first go through the project's readme and then raise any issue.
> 
> Once you have gone through the readme, inform me and then i will assign you the issue.

I go through that now , But I suggest to make a new different file so that it becomes easy to head directly to that file

here I attached the screenshots of the file I have work in them earlier.
![Screenshot 2024-10-22 104423](https://github.com/user-attachments/assets/e9a080cd-b83b-41ba-92dd-7e8236d8d41e)
![Screenshot 2024-10-22 104433](https://github.com/user-attachments/assets/a6497a63-0c35-4afd-94d9-d9c13e617fcb)
![Screenshot 2024-10-22 104442](https://github.com/user-attachments/assets/18675df2-8b38-4e47-ad84-1b0bcf90923f)

**Comment by Nikhil0-3** [comment]
If you want I would also like to add contributing.md file
It helps contributors about how should they raise PR and more.

**Comment by prrockzed** [comment]
For you 1 comment: I don't think the Code of Conduct needs any attention. Also I intentionally put it where it is, so that it doesn't mess up the front page. And why will a person want to go to a file to read it. It is seen directly on the screen.
![Screenshot 2024-10-22 at 1 07 49 PM](https://github.com/user-attachments/assets/1e5a6dba-374d-4b26-a08e-fdfec98e23fc)

As for your 2nd comment, i would really to copy paste my earlier answer(my 1st comment of this thread):
Ok. Please tell me why should i assign you the issue. Just curious: Have you gone through the project's readme?
I really encourage people to first go through the project's readme and then raise any issue.

**Comment by prrockzed** [comment]
Guess you don't have much to comment here. Hence closing the issue.
