### ISSUE TITLE
Missing Contributing.md file

### ISSUE THREAD

**Issue by archanasingh11** [prrockzed/nvimDev#3]
**Description:**  
The repository is missing a `CONTRIBUTING.md` file, which is essential for guiding contributors on how to properly contribute to the project. This file typically outlines important guidelines, such as how to report issues, create pull requests, code style conventions, and other contribution practices.

**Tasks:**  
- [ ] Create a `CONTRIBUTING.md` file.
- [ ] Include sections for:
  - Contribution guidelines (pull requests, issues, feature requests).
  - Code style and formatting rules.
  - Branching and commit message conventions.
  - Testing requirements before submitting code.
  - How to set up the development environment (if needed).
  - Any other project-specific instructions.
- [ ] Review with the project maintainers and refine the guidelines.

Please @prrockzed  assign me this task label  "GSSOC-Ext" , "Hacktoberfest-accepted" and "level1" .

**Comment by prrockzed** [comment]
If you check out the readme carefully, just below the nvimDev heading(it is line 2 actually) there is a contribute button. Click on it to go to the CONTRIBUTING.md file🙃.
So, the CONTRIBUTING.md file is in the .github folder. I deliberately put it there so that there is less congestion at the start of the repo. Btw, if you want to contribute just check out the my other issues, you just have to check whether the project is running on a windows machine or not.

**Comment by prrockzed** [comment]
I am assuming you have nothing more to add here. Hence closing this issue.
